// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/InvReplaceForxyz.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class InvReplaceForxyz {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alph=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=28;
      if ($opEqualY($invokeField("length",args),0)) {
        $line=28;
        Alph=$fix(GCollections.asSet('a','c','t'));
      }
      else {
        $line=30;
        gold.structures.set.ISet $v1=$newSet();
        int $v3=$int(0);
        int $v4=$int($invokeMethod("length",((java.lang.String[])args)[$int(0)],new Object[]{}))-1;
        $v2:for (int i=$v3; i<=$v4; i++) {
          $v1.add($invokeMethod("charAt",((java.lang.String[])args)[$int(0)],new Object[]{i}));
        }
        Alph=$fix($opDiffeY($v1,GCollections.asSet('$','#')));
      }
      $line=35;
      Object deCoder=$fix(InvReplaceForxyz.createTransducer(Alph));
      $line=36;
      System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY($opAdditY("Input strings of the form xyz:W#. with x, y, over ",Alph),"and W  over   "),Alph),"* (end with an empty string)")}));
      $line=39;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,InvReplaceForxyz.class,"main",$line);
    }
  }
  public static ITransducer createTransducer(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=48;
      Object Ls=$fix(A);
      $line=49;
      Object M0=$fix(GCollections.asSet(""));
      $line=50;
      gold.structures.set.ISet $v5=$newSet();
      $v6:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        $v5.add($opAdditY("",a));
      }
      Object M1=$fix($v5);
      $line=51;
      gold.structures.set.ISet $v7=$newSet();
      $v8:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(a)))) {
          $v7.add($opAdditY($opAdditY("",a),b));
        }
      }
      Object M2=$fix($v7);
      $line=52;
      gold.structures.set.ISet $v9=$newSet();
      $v10:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(a)))) {
          for (Object c:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(b,a)))) {
            $v9.add($opAdditY($opAdditY($opAdditY("",a),b),c));
          }
        }
      }
      Object M3=$fix($v9);
      $line=53;
      gold.structures.set.ISet $v11=$newSet();
      $v12:for (Object s:GCollections.unmodifiableCollection($opUnionY($opUnionY($opUnionY(M1,M2),M3),M0))) {
        $v11.add(GCollections.asList(s));
      }
      gold.structures.set.ISet $v13=$newSet();
      $v14:for (Object s:GCollections.unmodifiableCollection(M3)) {
        int $v15=$int(0);
        int $v16=$int(2);
        for (int d=$v15; d<=$v16; d++) {
          $v13.add(GCollections.asList(s,d));
        }
      }
      Object Q=$fix($opUnionY($opUnionY($v11,$v13),GCollections.asSet("E","F")));
      $line=54;
      System.out.println($message(new Object[]{Q}));
      $line=56;
      Object \u03A3=$fix($opUnionY(A,GCollections.asSet('#',':')));
      $line=57;
      Object O=$fix($opUnionY(\u03A3,GCollections.asSet('$')));
      $line=58;
      Object q_0=$fix(GCollections.asList(""));
      $line=59;
      Object F=$fix(GCollections.asSet("F"));
      $line=60;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,O,\u03A3,q_0,F,new GMethod(InvReplaceForxyz.class,"\u03B41"),new GMethod(InvReplaceForxyz.class,"g"),new GMethod(InvReplaceForxyz.class,"h1")});
      if (true) break $try;
      $line=61;
      $rethrow(new RuntimeException("The function \"createTransducer(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,InvReplaceForxyz.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object g(Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $result="";
      if (true) break $try;
      $line=62;
      $rethrow(new RuntimeException("The function \"g(x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,InvReplaceForxyz.class,"g",$line);
    }
    return $result;
  }
  public static Object \u03B41(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=70;
      String s=null;
      s=$defaultValue(String.class);
      $line=72;
      if (($opEqualY(q,"E")||$opEqualY(q,"F"))) {
        $line=73;
        $result="E";
        if (true) break $try;
      }
      else {
        $line=74;
        if ($opEqualY($opAbsolY(q),1)) {
          $line=75;
          s=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
          $line=76;
          if (((($opEqualY(((java.lang.String)s).length(),0)&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))&&!$opEqualY(\u03C3,'$'))) {
            $line=77;
            $result=GCollections.asList($opAdditY("",\u03C3));
            if (true) break $try;
          }
          else {
            $line=78;
            if ((((($opEqualY(((java.lang.String)s).length(),1)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))&&!$opEqualY(\u03C3,'$'))) {
              $line=79;
              $result=GCollections.asList($opAdditY($opAdditY("",s),\u03C3));
              if (true) break $try;
            }
            else {
              $line=80;
              if (((((($opEqualY(((java.lang.String)s).length(),2)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))&&!$opEqualY(\u03C3,'$'))) {
                $line=81;
                $result=GCollections.asList($opAdditY($opAdditY("",s),\u03C3));
                if (true) break $try;
              }
              else {
                $line=82;
                if (($opEqualY(((java.lang.String)s).length(),3)&&$opEqualY(\u03C3,':'))) {
                  $line=83;
                  $result=GCollections.asList(s,0);
                  if (true) break $try;
                }
                else {
                  $line=85;
                  $result="E";
                  if (true) break $try;
                }
              }
            }
          }
        }
        else {
          $line=88;
          Object $v17=$getArrayValue(q,new Object[]{0});
          Object $v18=$getArrayValue(q,new Object[]{1});
          s=$cast(String.class,$fix($v17));
          Object p=$fix($v18);
          $line=89;
          if ($opEqualY(\u03C3,':')) {
            $line=89;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=90;
            if ($opEqualY(\u03C3,'#')) {
              $line=90;
              $result="F";
              if (true) break $try;
            }
            else {
              $line=91;
              if ($opEqualY(\u03C3,'$')) {
                $line=91;
                $result=GCollections.asList(s,0);
                if (true) break $try;
              }
              else {
                $line=93;
                if (($opEqualY(p,0)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                  $line=93;
                  $result=GCollections.asList(s,1);
                  if (true) break $try;
                }
                else {
                  $line=94;
                  if ($opEqualY(p,0)) {
                    $line=94;
                    $result=GCollections.asList(s,0);
                    if (true) break $try;
                  }
                  else {
                    $line=95;
                    if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                      $line=95;
                      $result=GCollections.asList(s,1);
                      if (true) break $try;
                    }
                    else {
                      $line=96;
                      if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))) {
                        $line=96;
                        $result=GCollections.asList(s,2);
                        if (true) break $try;
                      }
                      else {
                        $line=97;
                        if ($opEqualY(p,1)) {
                          $line=97;
                          $result=GCollections.asList(s,0);
                          if (true) break $try;
                        }
                        else {
                          $line=98;
                          if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                            $line=98;
                            $result=GCollections.asList(s,1);
                            if (true) break $try;
                          }
                          else {
                            $line=99;
                            if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(2))))) {
                              $line=99;
                              $result="E";
                              if (true) break $try;
                            }
                            else {
                              $line=101;
                              $result=GCollections.asList(s,0);
                              if (true) break $try;
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=104;
      $rethrow(new RuntimeException("The function \"\u03B41(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,InvReplaceForxyz.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object h1(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=107;
      String s=null;
      s=$defaultValue(String.class);
      $line=108;
      if (($opEqualY(q,"E")||$opEqualY(q,"F"))) {
        $line=109;
        $result="";
        if (true) break $try;
      }
      else {
        $line=110;
        if ($opEqualY($opAbsolY(q),2)) {
          $line=111;
          Object $v19=$getArrayValue(q,new Object[]{0});
          Object $v20=$getArrayValue(q,new Object[]{1});
          s=$cast(String.class,$fix($v19));
          Object p=$fix($v20);
          $line=112;
          if ($opEqualY(\u03C3,'#')) {
            $line=112;
            $result="#";
            if (true) break $try;
          }
          else {
            $line=113;
            if ($opEqualY(\u03C3,'$')) {
              $line=113;
              $result=s;
              if (true) break $try;
            }
            else {
              $line=114;
              if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(2))))) {
                $line=114;
                $result="";
                if (true) break $try;
              }
              else {
                $line=115;
                $result=\u03C3;
                if (true) break $try;
              }
            }
          }
        }
        else {
          $line=117;
          if ($opEqualY(\u03C3,'$')) {
            $line=117;
            $result="";
            if (true) break $try;
          }
          else {
            $line=118;
            $result=\u03C3;
            if (true) break $try;
          }
        }
      }
      $line=120;
      $rethrow(new RuntimeException("The function \"h1(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,InvReplaceForxyz.class,"h1",$line);
    }
    return $result;
  }
}
