// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/ReplaceForxyz.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class ReplaceForxyz {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alph=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=27;
      if ($opEqualY($invokeField("length",args),0)) {
        $line=27;
        Alph=$fix(GCollections.asSet('a','c','t'));
      }
      else {
        $line=29;
        gold.structures.set.ISet $v1=$newSet();
        int $v3=$int(0);
        int $v4=$int($invokeMethod("length",((java.lang.String[])args)[$int(0)],new Object[]{}))-1;
        $v2:for (int i=$v3; i<=$v4; i++) {
          $v1.add($invokeMethod("charAt",((java.lang.String[])args)[$int(0)],new Object[]{i}));
        }
        Alph=$fix($opDiffeY($v1,GCollections.asSet('$','#')));
      }
      $line=34;
      Object coder=$fix(ReplaceForxyz.createTransducer(Alph));
      $line=35;
      System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY($opAdditY("Input strings of the form xyz:W#. with x, y, over ",Alph),"and W  over   "),Alph),"* (end with an empty string)")}));
      $line=38;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,coder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"main",$line);
    }
  }
  public static ITransducer createTransducer(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=45;
      Object Ls=$fix(A);
      $line=46;
      Object M0=$fix(GCollections.asSet(""));
      $line=47;
      gold.structures.set.ISet $v5=$newSet();
      $v6:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        $v5.add($opAdditY("",a));
      }
      Object M1=$fix($v5);
      $line=48;
      gold.structures.set.ISet $v7=$newSet();
      $v8:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(a)))) {
          $v7.add($opAdditY($opAdditY("",a),b));
        }
      }
      Object M2=$fix($v7);
      $line=49;
      gold.structures.set.ISet $v9=$newSet();
      $v10:for (Object a:GCollections.unmodifiableCollection(Ls)) {
        for (Object b:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(a)))) {
          for (Object c:GCollections.unmodifiableCollection($opDiffeY(Ls,GCollections.asSet(b,a)))) {
            $v9.add($opAdditY($opAdditY($opAdditY("",a),b),c));
          }
        }
      }
      Object M3=$fix($v9);
      $line=50;
      gold.structures.set.ISet $v11=$newSet();
      $v12:for (Object s:GCollections.unmodifiableCollection($opUnionY($opUnionY($opUnionY(M1,M2),M3),M0))) {
        $v11.add(GCollections.asList(s));
      }
      gold.structures.set.ISet $v13=$newSet();
      $v14:for (Object s:GCollections.unmodifiableCollection(M3)) {
        int $v15=$int(0);
        int $v16=$int(2);
        for (int d=$v15; d<=$v16; d++) {
          $v13.add(GCollections.asList(s,d));
        }
      }
      Object Q=$fix($opUnionY($opUnionY($v11,$v13),GCollections.asSet("E","F")));
      $line=51;
      System.out.println($message(new Object[]{Q}));
      $line=53;
      Object \u03A3=$fix($opUnionY(A,GCollections.asSet('#',':')));
      $line=54;
      Object O=$fix($opUnionY(\u03A3,GCollections.asSet('$')));
      $line=55;
      Object q_0=$fix(GCollections.asList(""));
      $line=56;
      Object F=$fix(GCollections.asSet("F"));
      $line=57;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,O,q_0,F,new GMethod(ReplaceForxyz.class,"\u03B4"),new GMethod(ReplaceForxyz.class,"g"),new GMethod(ReplaceForxyz.class,"h")});
      if (true) break $try;
      $line=58;
      $rethrow(new RuntimeException("The function \"createTransducer(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object g(Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $result="";
      if (true) break $try;
      $line=62;
      $rethrow(new RuntimeException("The function \"g(x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"g",$line);
    }
    return $result;
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=66;
      String s=null;
      s=$defaultValue(String.class);
      $line=68;
      if (($opEqualY(q,"E")||$opEqualY(q,"F"))) {
        $line=69;
        $result="E";
        if (true) break $try;
      }
      else {
        $line=70;
        if ($opEqualY($opAbsolY(q),1)) {
          $line=71;
          s=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
          $line=72;
          if ((($opEqualY(((java.lang.String)s).length(),0)&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))) {
            $line=73;
            $result=GCollections.asList($opAdditY("",\u03C3));
            if (true) break $try;
          }
          else {
            $line=74;
            if (((($opEqualY(((java.lang.String)s).length(),1)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))) {
              $line=75;
              $result=GCollections.asList($opAdditY($opAdditY("",s),\u03C3));
              if (true) break $try;
            }
            else {
              $line=76;
              if ((((($opEqualY(((java.lang.String)s).length(),2)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))&&!$opEqualY(\u03C3,'#'))&&!$opEqualY(\u03C3,':'))) {
                $line=77;
                $result=GCollections.asList($opAdditY($opAdditY("",s),\u03C3));
                if (true) break $try;
              }
              else {
                $line=78;
                if (($opEqualY(((java.lang.String)s).length(),3)&&$opEqualY(\u03C3,':'))) {
                  $line=79;
                  $result=GCollections.asList(s,0);
                  if (true) break $try;
                }
                else {
                  $line=81;
                  $result="E";
                  if (true) break $try;
                }
              }
            }
          }
        }
        else {
          $line=84;
          Object $v17=$getArrayValue(q,new Object[]{0});
          Object $v18=$getArrayValue(q,new Object[]{1});
          s=$cast(String.class,$fix($v17));
          Object p=$fix($v18);
          $line=85;
          if ($opEqualY(\u03C3,':')) {
            $line=85;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=86;
            if ($opEqualY(\u03C3,'#')) {
              $line=86;
              $result="F";
              if (true) break $try;
            }
            else {
              $line=87;
              if (($opEqualY(p,0)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                $line=87;
                $result=GCollections.asList(s,1);
                if (true) break $try;
              }
              else {
                $line=88;
                if ($opEqualY(p,0)) {
                  $line=88;
                  $result=GCollections.asList(s,0);
                  if (true) break $try;
                }
                else {
                  $line=89;
                  if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                    $line=89;
                    $result=GCollections.asList(s,1);
                    if (true) break $try;
                  }
                  else {
                    $line=90;
                    if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))) {
                      $line=90;
                      $result=GCollections.asList(s,2);
                      if (true) break $try;
                    }
                    else {
                      $line=91;
                      if ($opEqualY(p,1)) {
                        $line=91;
                        $result=GCollections.asList(s,0);
                        if (true) break $try;
                      }
                      else {
                        $line=92;
                        if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                          $line=92;
                          $result=GCollections.asList(s,1);
                          if (true) break $try;
                        }
                        else {
                          $line=93;
                          $result=GCollections.asList(s,0);
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=96;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=100;
      String s=null;
      s=$defaultValue(String.class);
      $line=101;
      if (($opEqualY(q,"E")||$opEqualY(q,"F"))) {
        $line=102;
        $result="";
        if (true) break $try;
      }
      else {
        $line=103;
        if ($opEqualY($opAbsolY(q),1)) {
          $line=104;
          s=$cast(String.class,$fix($getArrayValue(q,new Object[]{0})));
          $line=105;
          if ($opEqualY(((java.lang.String)s).length(),0)) {
            $line=106;
            $result=$opAdditY("",\u03C3);
            if (true) break $try;
          }
          else {
            $line=107;
            if (($opEqualY(((java.lang.String)s).length(),1)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
              $line=108;
              $result=$opAdditY("",\u03C3);
              if (true) break $try;
            }
            else {
              $line=109;
              if ((($opEqualY(((java.lang.String)s).length(),2)&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))&&!$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))) {
                $line=110;
                $result=$opAdditY("",\u03C3);
                if (true) break $try;
              }
              else {
                $line=111;
                if (($opEqualY(((java.lang.String)s).length(),3)&&$opEqualY(\u03C3,':'))) {
                  $line=112;
                  $result=":";
                  if (true) break $try;
                }
                else {
                  $line=113;
                  $result="";
                  if (true) break $try;
                }
              }
            }
          }
        }
        else {
          $line=116;
          Object $v19=$getArrayValue(q,new Object[]{0});
          Object $v20=$getArrayValue(q,new Object[]{1});
          s=$cast(String.class,$fix($v19));
          Object p=$fix($v20);
          $line=117;
          if ($opEqualY(\u03C3,'#')) {
            $line=117;
            $result=$opAdditY(((java.lang.String)s).substring($int(0),$int(p)),"#");
            if (true) break $try;
          }
          else {
            $line=118;
            if (($opEqualY(p,0)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
              $line=118;
              $result="";
              if (true) break $try;
            }
            else {
              $line=119;
              if ($opEqualY(p,0)) {
                $line=119;
                $result=$opAdditY("",\u03C3);
                if (true) break $try;
              }
              else {
                $line=120;
                if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                  $line=120;
                  $result=((java.lang.String)s).charAt($int(0));
                  if (true) break $try;
                }
                else {
                  $line=121;
                  if (($opEqualY(p,1)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(1))))) {
                    $line=121;
                    $result="";
                    if (true) break $try;
                  }
                  else {
                    $line=122;
                    if ($opEqualY(p,1)) {
                      $line=122;
                      $result=$opAdditY($opAdditY("",((java.lang.String)s).charAt($int(0))),\u03C3);
                      if (true) break $try;
                    }
                    else {
                      $line=123;
                      if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(0))))) {
                        $line=123;
                        $result=$opAdditY($opAdditY("",((java.lang.String)s).charAt($int(0))),((java.lang.String)s).charAt($int(1)));
                        if (true) break $try;
                      }
                      else {
                        $line=124;
                        if (($opEqualY(p,2)&&$opEqualY(\u03C3,((java.lang.String)s).charAt($int(2))))) {
                          $line=124;
                          $result="$";
                          if (true) break $try;
                        }
                        else {
                          $line=125;
                          $result=$opAdditY($opAdditY($opAdditY("",((java.lang.String)s).charAt($int(0))),((java.lang.String)s).charAt($int(1))),\u03C3);
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=128;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ReplaceForxyz.class,"h",$line);
    }
    return $result;
  }
}
